channels:
  - conda-forge
dependencies:
  - python>=3
  - sphinx>=1.6
  - pandoc
  - nbconvert!=5.4
  - ipykernel
  - numpy
  - matplotlib
  - pandas
  - sphinxcontrib-bibtex
  - pip:
    - sphinxcontrib-svg2pdfconverter
